name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NAME: frontend

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.x'

    - uses: actions/checkout@v6

    - name: Tests
      run: make test

  test-short:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.x'

    - name: Tests
      run: make test-short

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.x'

    - name: Build
      run: go build -v ./...
